### ISSUE TITLE
Create a parseable *_str version

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/DiceRolls.jl#4]
For instance

```julia
macro r_str(str)
    # Parse the string and call appropriate functions
end
```
so that it's easier to run with bots, for instance.

Examples of rolls that would be interesting:

```julia
r"2#1d20+6" # Rolls 1d20+6 twice
r"2d20kh1" # Rolls 2d20 and keeps highest
r"Adv 1d20+6" # Rolls  1d20+6 twice and keeps highest (same as `kh1`).
```

cf. @jualns @Lucas-Akio

**Comment by Moelf** [comment]
btw:
> Invalid
Your PR has been labeled as "invalid" or "spam" by a maintainer and won't count toward winning Hacktoberfest.

**Comment by abelsiqueira** [comment]
The topic was added, let me know if it works, and thanks again.
